-- ⚠️ Fichier remplacé par la migration complète : `supabase/profiles.sql`
-- Exécuter `profiles.sql` dans Supabase SQL Editor.
--
-- Buckets Storage (dashboard, hors SQL) :
--   - `avatars` (public en lecture recommandé)
--   - `banners` (public en lecture recommandé)
--
-- Exemple policy storage (à adapter) :
-- create policy "avatars_authenticated_upload"
--   on storage.objects for insert to authenticated
--   with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
